#!/usr/bin/env bash

while read symbol
do
    lc_symbol=$(echo ${symbol} | tr '[:upper:]' '[:lower:]')
    echo "importing ${symbol}"
    echo ".import data/history/${symbol}.csv ${lc_symbol}_stock" | sqlite3 -csv data/trading.db
done < /dev/stdin
