#!/usr/bin/env bash

TODAY=`date +%s`
if [ -z "$2" ]
then
    START_DATE=${TODAY}
else
    START_DATE=$(date -j -f '%Y-%m-%d' $2 +%s)
fi
QUERY="period1=${START_DATE}"
QUERY="${QUERY}&period2=${TODAY}"
QUERY="${QUERY}&interval=1d"
QUERY="${QUERY}&events=history"
QUERY="${QUERY}&crumb=${YAHOO_CRUMB}"

curl -s "https://query1.finance.yahoo.com/v7/finance/download/$1?${QUERY}" \
    -H"cookie: ${YAHOO_COOKIE}"
