# sinusoidal-ish wave
data = [
    { 'change': 0  },
    { 'change': -1 },
    { 'change': -1 },
    { 'change': 0  },
    { 'change': 1  },
    { 'change': 1  },
    { 'change': 1  },
    { 'change': 0  },
    { 'change': -1 },
    { 'change': -1 },
    { 'change': -1 },
    { 'change': 0  },
    { 'change': 1  },
    { 'change': 1  },
    { 'change': 1  },
    { 'change': 0  },
    { 'change': -1 },
]
