# sinusoidal-ish wave
data = [
    { 'change': 0, 'action': None, 'return': None },
    { 'change': -1, 'action': None, 'return': None },
    { 'change': -1, 'action': None, 'return': None },
    { 'change': 0, 'action': None, 'return': None },
    { 'change': 1, 'action': None, 'return': None },
    { 'change': 1, 'action': None, 'return': None },
    { 'change': 1, 'action': None, 'return': None },
    { 'change': 0, 'action': None, 'return': None },
    { 'change': -1, 'action': None, 'return': None },
    { 'change': -1, 'action': None, 'return': None },
    { 'change': -1, 'action': None, 'return': None },
    { 'change': 0, 'action': None, 'return': None },
    { 'change': 1, 'action': None, 'return': None },
    { 'change': 1, 'action': None, 'return': None },
    { 'change': 1, 'action': None, 'return': None },
    { 'change': 0, 'action': None, 'return': None },
    { 'change': -1, 'action': None, 'return': None },
]
